---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Test DockerHub Secrets
        run: |
          echo "DockerHub User: ${{ secrets.DOCKERHUB_USER }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: sudo docker-compose run --run app sh -c "python manage.ph test"
      - name: Lint
        run: sudo docker-compose run --run app sh -c "flake8"
